### PR TITLE
feat: add indentation on wrapped lines

### LINKED ISSUE #228: long string overflowed the vertical gray line when wrap
Hi,
Thanks for ur work.However, it seemes there are still two issue exist in 0.14.9.
First,  in text mode, long string overflowed the vertical gray line when wrap. The long string is in one node In successor, but it divide into muti nodes in classic.

image

The other is about plain obj and array  when format. It works normal when parser is default. But when i changed it into LosslessJSONParser, plain obj and array expand again like https://github.com/josdejong/svelte-jsoneditor/issues/220
What shuold i do to solve this ?

### PR DESCRIPTION
**Pull request by fauzi9331**
resolves #228

Hi, in this PR, I've created a custom decoration to add 'padding-left' and 'text-indent' to each line so that the wrapped lines also have indentation.
I used '@replit/codemirror-indentation-markers' as a reference to build this decoration and even copied one of their utility functions, getVisibleLines.
I'm not sure if I put the file in the correct directory, nor am I sure what tests I should do to ensure that I don't break anything. If you can advice, that would be great

image

### CODE REVIEW

**Comment by josdejong** [comment]
@fauzi9331 I have tried out your PR and it works like a charm, really nice! It is really much nicer for the eye. I've also tried with large documents and I don't see any performance problems or things that break.

Some thoughts:

1. I can imagine this is a feature that quite some people would like to have in codemirror. Would it be an idea to publish this as a standalone plugin for CodeMirror, similar to `@replit/codemirror-indentation-markers`?
2. Is it possible to let this plugin respect the configured indentation for the editor? It is now hardcoded with an indentation of 2, but if a user configures the editor with 4 spaces instead it would be nice if the wrapped lines adhere to that setting too.
3. The directory where you've put `wrappedLineIndentation.js` makes sense to me.
4. Can you resolve the conflict with the `main` branch? (it's a simple one)

**Comment by josdejong** [comment]
@fauzi9331 did you see my comments of last week?

**Comment by fauzi9331** [comment]
Hi @josdejong sorry for not replying sooner. Thank you for following up.
I really appreciate the feedback, let me try to publish it as a standalone plugin, this will be my first published package. 
I'll also address the other points and update the PR.

**Comment by fauzi9331** [comment]
Hi @josdejong sorry for taking a long time. I've been busy with work and studies lately

Here's the update:

- Published `wrappedLineIndentation.js` as a standalone plugin.
- Ensured the plugin respects the indentation setting.
- Resolved the conflict

image

**Comment by josdejong** [comment]
Thanks a lot @fauzi9331 , this looks very neat! The configurable indentation indeed works like a charm.

I see there is a linting issue and a failing test due to an outdated snapshot, I'll fix that right away.

**Comment by fauzi9331** [comment]
Hi @josdejong no reason for it. I just chose to start from 0 😆

**Comment by josdejong** [comment]
Can you publish it as v1.0.0? That indicates that it is mature and feature complete rather than "your first commit".

**Comment by fauzi9331** [comment]
@josdejong I have bumped the version to 1.0.0. there's no change in the code. do you want me to make new PR to update the version here too?

**Comment by josdejong** [comment]
Thanks! 

I'll update all dependencies including `codemirror-wrapped-line-indent` before the first next release, that will be alright.

**Pull request merged**
