### PR TITLE
Add onselect

### PR DESCRIPTION
**Pull request by iliakap**

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @iliakap for your PR, I'll look into it after the holidays

**Comment by josdejong** [comment]
Thanks again for your PR @iliakap .

For reference: this PR will resolve #163.

Two questions:

1. Right now, the `onSelect` will work for `tree` and `table` mode, but not for `text` mode. I think we need to at least have a clear plan on how to implement support for selection for `text` mode: either a different method, or via an extra parameter or so. What are your thoughts on that?
2. Besides listening for changes in the selection, we'll also need a way to _change_ the selection, like I describe in https://github.com/josdejong/svelte-jsoneditor/issues/163#issuecomment-1277397051. What do you think?

**Comment by josdejong** [comment]
Closing this PR now due to lack of response. Feel free to reopen if needed.

**Comment by iliakap** [comment]
@josdejong, just saw ur comments, sorry for the late response :)
I wont reopen now since I'll only have time to look at it in a few weeks. 
with regards to your questions:
1. having hard time to remember, but I recall the text mode is just free text, I think it can be implemented using the [web selection api](https://developer.mozilla.org/en-US/docs/Web/API/Selection), but it felt out of scope.
2. I agree it's a nice addition, LMK if you wanna add this to this PR, not sure what the timeline will be though :)

**Comment by josdejong** [comment]
Thanks for getting back @iliakap, no problem at all. Let's continue the discussion in #163

**Pull request closed without merging**
