### PR TITLE
fix: replace `debug` with a util debug function

### PR DESCRIPTION
**Pull request by josdejong**
@milahu can you have a look at this PR?

For reference: #33, #31.

### CODE REVIEW

**Comment by josdejong** [comment]
I would like to see if it is possible to use some environment variable of Svelte to detect whether running in development or production, and use that to enable/disable logging. It would be cool to see if we can utilize dead code elimination of all the debug lines when in production.

**Comment by milahu** [comment]
lgtm : )

> dead code elimination

can we micro optimize this later? ; )

**Comment by josdejong** [comment]
Thanks.

> can we micro optimize this later? ; )

😂  yes. This new solution already has much less lines of code, so it's already an improvement anyway.

**Comment by josdejong** [comment]
Published now in `v0.3.6`

**Pull request merged**
