### PR TITLE
devDependencies: add rollup

### PR DESCRIPTION
**Pull request by milahu**
add rollup to devDependencies

why?
pnpm thinks its smarter than the npm standard
and [pnpm will refuses to install peerDependencies ...](https://github.com/pnpm/pnpm/issues/827)

todo update package lock

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks, fine with me to add rollup, thanks for your PR. Can you remove the hat `^` from the version number to make it exact?

**Comment by milahu** [comment]
> to make it exact

package-lock.json ...?

**Comment by josdejong** [comment]
> > to make it exact
> 
> package-lock.json ...?

😂 maybe you're right and I should update my best-practices ("just use exact versions to stay out of trouble"). Still I do like plain and simple strict versions.

**Comment by josdejong** [comment]
Merged now 👍

**Pull request merged**
