### PR TITLE
refactor: started to move to typescript

### PR DESCRIPTION
**Pull request by tylerjlawson**
I have only just started to refactor this. There is a lot of changing filenames and typing things out that needs to happen still. Figured I'd start this draft MR and see if anyone would be kind enough to help with the move to Typescript.

Relates to #19

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks a lot Tyler! This is a nice start. 

To me, the most important thing to get right first is the configuration of build scripts and dev environment. After that, we can gradually migrate all code to TypeScript. Right now, when I try out your PR it mostly doesn't work 😁  

Concretely, the following scripts should keep working:

1. `npm run dev` -> after that open the dev environment in your browser at http://localhost:3000
2. `npm test` -> runs the unit tests
3. `npm run build` -> generates the npm package and bundles in `/package`. Test by opening `/tools/develop_vanilla.html` in your browser

**Comment by tylerjlawson** [comment]
@josdejong I was able to fix `npm run dev` and `npm run build` as far as I could tell. It was hard to test the success of these though because the unit tests are still broken. 

I followed the advice here: https://github.com/TypeStrong/ts-node/issues/935#issuecomment-913179458, but was unable to get the tests working (I am not super familiar with working with esm). Figured I'd see if you have any thoughts on this bit before continuing to debug - thanks!

**Comment by tylerjlawson** [comment]
It looks like that fix was merged: https://github.com/microsoft/TypeScript/pull/44501#issuecomment-926960500

I can try bumping typescript over the weekend to see if the issue is resolved, but as I followed that thread there seem to be some more lingering issues. I'll keep my fingers crossed 🤞

**Comment by tylerjlawson** [comment]
Updating this with a more recent thread of lingering TS issues: https://github.com/microsoft/TypeScript/issues/46452

**Comment by josdejong** [comment]
👍

**Comment by josdejong** [comment]
I've now (finally) fixed the TypeScript setup, it's in the `main` branch already (many files still need to be converted to TS but there is a start). I'll close this PR now, thanks again Tyler.

**Pull request closed without merging**
